name: mca_flutter_sdk
description: The Official Flutter MyCover.ai SDK for insurance purchase and payment. Completely supports Android and iOS.
version: 0.0.4
homepage: https://github.com/ibuildgenius/mca-flutter-sdk


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  fluttertoast: ^8.0.8
  image_picker: ^0.8.1
  mockito: ^5.0.3
  camera: ^0.9.4+14
  get:
  video_compress: ^3.1.0
  permission_handler: ^9.2.0
  geolocator: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/
